mesh2sdf:
  # surface point cloud settings
  surface_point_method: 'scan'
  scan_count: 20
  scan_resolution: 400
  sample_point_count: 10000000
  calculate_normals: True
  # voxelization/sdf settings
  voxel_resolution: 128
  use_depth_buffer: True
  normal_sample_count: 11
  pad: False
  check_result: True
  return_gradients: True

mesh2sdf_floodfill:
  # settings for the floodfill sdf gen algs
  # relative-path wrt. to script, NOT CONFIG, of the binary
  exe_path: './src/utils/sdf_gen/mesh2sdf_floodfill/ubuntu2004_cu113_binary/sdf_gen'
  # resolution of the voxel grid
  resolution: 0.002
  # surface truncation distance in voxels
  # does not actually affect SDF computation
  trunc: 5
  # outter padding for voxel grid
  pad: 5
  # set True to normalize mesh to unit cube
  normalize: False